# https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg
version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  PostgresSQL:
    image: "postgres:9.6-alpine"
    container_name: soccermetrics-postgres
    volumes:
      - soccermetrics-data::/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB:soccermetrics
      - POSTGRES_USER:soccermetrics
      - POSTGRES_PASSWORD:soccermetrics

  Frontend:
    build: ./Frontend
    container_name: soccermetrics-frontend
    expose:
      - "80"

volumes:
  soccermetrics-data: